name: bvrit
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  expandable: ^4.1.2
  flutter_linkify: ^3.1.0
  url_launcher: ^5.4.1
  amazon_s3_cognito: ^0.2.3
  amazon_cognito_identity_dart: ^0.0.22
  file_picker: ^1.4.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/alucard.jpg
    - assets/index.jpg
